## Make coco splits

In [4]:
from pylabel import importer, exporter, dataset
import numpy as np
from sklearn.model_selection import train_test_split
import json
import os
import pandas as pd

#### Save the entire dataset to coco if needed

In [2]:
voc_path = '/home/gridsan/manderson/ovdsat/data/dior'

In [3]:
import os

ann_path = voc_path + "/Annotations"
img_path = voc_path + "/JPEGImages"

num_ann = len([f for f in os.listdir(ann_path) if f.endswith(".xml")])
num_img = len([f for f in os.listdir(img_path) if f.endswith((".jpg", ".jpeg", ".png"))])

print("XML files:", num_ann)
print("Images:", num_img)

XML files: 23463
Images: 23463

In [14]:
import os

# Path to your images
img_path = voc_path + "/JPEGImages"

# List all files ending with .jpg
files = [f for f in os.listdir(img_path) if f.endswith(".jpg")]

# Extract numeric part of filenames
numbers = sorted([int(f.split('.')[0]) for f in files])

# Expected full range
expected = set(range(numbers[0], numbers[-1] + 1))

# Find missing numbers
missing = sorted(expected - set(numbers))

print(f"Total missing files: {len(missing)}")
print("Missing file numbers:", missing)

Total missing files: 0
Missing file numbers: []

In [4]:
mydataset = importer.ImportVOC(path = voc_path+'/Annotations', path_to_images=voc_path+'/JPEGImages', name='DIOR')

Importing VOC files...: 100%|██████████| 23464/23464 [01:51<00:00, 211.21it/s]

In [6]:
print(len(mydataset.df))
mydataset.df.head()

192518

,img_folder,img_filename,img_path,img_id,img_width,img_height,img_depth,ann_segmented,ann_bbox_xmin,ann_bbox_ymin,...,ann_iscrowd,ann_keypoints,ann_pose,ann_truncated,ann_difficult,cat_id,cat_name,cat_supercategory,split,annotated
id,,,,,,,,,,,,,,,,,,,,,
0,/home/gridsan/manderson/ovdsat/data/dior/JPEGI...,16848.jpg,NaN,0,800,800,3,0,675.0,748.0,...,NaN,NaN,Unspecified,,,0,ship,NaN,,1
1,/home/gridsan/manderson/ovdsat/data/dior/JPEGI...,16848.jpg,NaN,0,800,800,3,0,639.0,770.0,...,NaN,NaN,Unspecified,,,0,ship,NaN,,1
2,/home/gridsan/manderson/ovdsat/data/dior/JPEGI...,16848.jpg,NaN,0,800,800,3,0,500.0,548.0,...,NaN,NaN,Unspecified,,,0,ship,NaN,,1
3,/home/gridsan/manderson/ovdsat/data/dior/JPEGI...,16848.jpg,NaN,0,800,800,3,0,540.0,487.0,...,NaN,NaN,Unspecified,,,0,ship,NaN,,1
4,/home/gridsan/manderson/ovdsat/data/dior/JPEGI...,16848.jpg,NaN,0,800,800,3,0,444.0,391.0,...,NaN,NaN,Unspecified,,,0,ship,NaN,,1

In [19]:
# FOR SIMD ONLY: fix categories!
# print(len(mydataset.df))
# mydataset.df.loc[mydataset.df['cat_id'] == '14', 'cat_id'] = '11'
# mydataset.df.loc[mydataset.df['cat_id'] == '16', 'cat_id'] = '10'
# mydataset.df['img_filename'] = mydataset.df['img_filename'] + '.jpg'
# print(len(mydataset.df))

45310
45310

In [7]:
exp = exporter.Export(mydataset)
exp.ExportToCoco(output_path=f'{voc_path}/dior_coco_all.json', cat_id_index=0)

/home/gridsan/manderson/.conda/envs/test/lib/python3.9/site-packages/pylabel/exporter.py:767: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace(r"^\s*$", np.nan, regex=True)
Exporting to COCO file...: 100%|██████████| 192518/192518 [11:24<00:00, 281.44it/s]

['/home/gridsan/manderson/ovdsat/data/dior/dior_coco_all.json']

In [10]:
# Fix .xml -> jpg, if needed

coco_json = "/home/gridsan/manderson/ovdsat/data/mar/mar_coco_all.json"
images_dir = "/home/gridsan/manderson/ovdsat/data/mar/JPEGImages"
out_json = "/home/gridsan/manderson/ovdsat/data/mar/mar_coco_all_fixed.json"

with open(coco_json, "r") as f:
    coco = json.load(f)

num_fixed = 0
num_missing = 0

for img in coco["images"]:
    fname = img["file_name"]

    if fname.lower().endswith(".xml"):
        new_fname = fname[:-4] + ".jpg"
        jpg_path = os.path.join(images_dir, new_fname)

        if os.path.exists(jpg_path):
            img["file_name"] = new_fname
            num_fixed += 1
        else:
            print(f"[WARN] JPG not found for {fname}")
            num_missing += 1

with open(out_json, "w") as f:
    json.dump(coco, f)

print(f"Fixed {num_fixed} image entries")
print(f"Missing JPGs: {num_missing}")
print(f"Saved to: {out_json}")

Fixed 589 image entries
Missing JPGs: 0
Saved to: /home/gridsan/manderson/ovdsat/data/mar/mar_coco_all_fixed.json

In [44]:
for M in [1, 2, 3]:
    in_path = f'simd/old/train_coco_finetune_val-{M}.json'
    out_path = f'simd/train_coco_finetune_val-{M}.json'
    with open(in_path, "r") as f:
        coco = json.load(f)

    for img in coco["images"]:
        fname = img["file_name"]
        if not fname.lower().endswith(".jpg"):
            img["file_name"] = fname + ".jpg"

    with open(out_path, "w") as f:
        json.dump(coco, f, indent=4)

    print(f"Saved updated COCO to {out_path}")

Saved updated COCO to simd/train_coco_finetune_val-1.json
Saved updated COCO to simd/train_coco_finetune_val-2.json
Saved updated COCO to simd/train_coco_finetune_val-3.json

### RarePlanes

In [6]:
# Combine train and test coco files

file1 = "/home/gridsan/manderson/ovdsat/data/rareplanes/metadata_annotations/RarePlanes_Test_Coco_Annotations_tiled.json"
file2 = "/home/gridsan/manderson/ovdsat/data/rareplanes/metadata_annotations/RarePlanes_Train_Coco_Annotations_tiled.json"
output_file = "/home/gridsan/manderson/ovdsat/data/rareplanes/rareplanes_all.json"

with open(file1, "r") as f:
    data1 = json.load(f)

with open(file2, "r") as f:
    data2 = json.load(f)

next_image_id = max((x["id"] for x in data1["images"]), default=0) + 1
next_object_id = max(
    [x["id"] for x in data1["annotations"]] +
    [x["id"] for x in data1["categories"]],
    default=0
) + 1

image_id_map = {}
object_id_map = {}

# Remap images from file 2
for image in data2["images"]:
    old_id = image["id"]
    new_id = next_image_id
    next_image_id += 1

    image_id_map[old_id] = new_id

    new_image = image.copy()
    new_image["id"] = new_id
    data1["images"].append(new_image)

# Remap annotations from file 2
for annotation in data2["annotations"]:
    old_id = annotation["id"]
    new_id = next_object_id
    next_object_id += 1

    object_id_map[old_id] = new_id

    new_annotation = annotation.copy()
    new_annotation["id"] = new_id
    new_annotation["image_id"] = image_id_map[annotation["image_id"]]
    data1["annotations"].append(new_annotation)

# Remap RarePlanes category/aircraft metadata from file 2
for category in data2["categories"]:
    new_category = category.copy()
    new_category["id"] = object_id_map[category["id"]]
    new_category["image_id"] = image_id_map[category["image_id"]]
    data1["categories"].append(new_category)

with open(output_file, "w") as f:
    json.dump(data1, f)

print(f"Saved to: {output_file}")
print(f"Images: {len(data1['images'])}")
print(f"Annotations: {len(data1['annotations'])}")
print(f"Categories: {len(data1['categories'])}")

Saved to: /home/gridsan/manderson/ovdsat/data/rareplanes/rareplanes_all.json
Images: 8525
Annotations: 25205
Categories: 25205

In [5]:
# Reformat the Rareplanes metadata

input_file = "/home/gridsan/manderson/ovdsat/data/rareplanes/rareplanes_all.json"
output_file = "/home/gridsan/manderson/ovdsat/data/rareplanes/rareplanes_coco_all.json"
image_folder = "/home/gridsan/manderson/ovdsat/data/rareplanes/PNGImages"

with open(input_file, "r") as f:
    data = json.load(f)

# RarePlanes stores one aircraft metadata record per annotation.
metadata_by_id = {
    item["id"]: item
    for item in data["categories"]
}

# Create standard COCO categories from unique aircraft roles.
roles = sorted({
    item["role"]
    for item in data["categories"]
    if item.get("role")
})

role_to_category_id = {
    role: category_id
    for category_id, role in enumerate(roles)
}

categories = [
    {
        "id": category_id,
        "name": role,
        "supercategory": "aircraft"
    }
    for role, category_id in role_to_category_id.items()
]

# Reformat images.
images = []

for image in data["images"]:
    new_image = image.copy()
    new_image["folder"] = image_folder
    new_image["path"] = None
    new_image["depth"] = 3
    images.append(new_image)

# Reformat annotations while retaining all metadata.
annotations = []

for annotation in data["annotations"]:
    metadata = metadata_by_id.get(annotation["id"])

    if metadata is None:
        print(f"Skipping annotation {annotation['id']}: no matching metadata")
        continue

    role = metadata.get("role")

    if role not in role_to_category_id:
        print(f"Skipping annotation {annotation['id']}: missing role")
        continue

    # Keep every original annotation field.
    new_annotation = annotation.copy()

    # Add every RarePlanes metadata field except fields that would conflict
    # with the annotation's own identifiers and geometry.
    for key, value in metadata.items():
        if key not in {"id", "image_id", "bbox", "segmentation", "area"}:
            new_annotation[key] = value

    # Add/standardize expected annotation fields.
    new_annotation["category_id"] = role_to_category_id[role]
    new_annotation["segmented"] = (
        "1" if annotation.get("segmentation") else "0"
    )
    new_annotation["iscrowd"] = annotation.get("iscrowd", 0)
    new_annotation["pose"] = annotation.get("pose", "Unspecified")
    new_annotation["difficult"] = annotation.get("difficult")

    if new_annotation.get("area") is None:
        bbox = new_annotation["bbox"]
        new_annotation["area"] = bbox[2] * bbox[3]

    annotations.append(new_annotation)

output = {
    "images": images,
    "annotations": annotations,
    "categories": categories
}

with open(output_file, "w") as f:
    json.dump(output, f)

print(f"Saved to: {output_file}")
print(f"Images: {len(images)}")
print(f"Annotations: {len(annotations)}")
print(f"Categories: {len(categories)}")

print("\nCategory mapping:")
for category in categories:
    print(f"{category['id']}: {category['name']}")

Saved to: /home/gridsan/manderson/ovdsat/data/rareplanes/rareplanes_coco_all.json
Images: 8525
Annotations: 25205
Categories: 7

Category mapping:
0: Large Civil Transport/Utility
1: Medium Civil Transport/Utility
2: Military Bomber
3: Military Fighter/Interceptor/Attack
4: Military Trainer
5: Military Transport/Utility/AWAC
6: Small Civil Transport/Utility

In [22]:
# Remove Military Bomber (only 10 instances)

input_file = "/home/gridsan/manderson/ovdsat/data/rareplanes/rareplanes_coco_all-orig.json"
output_file = "/home/gridsan/manderson/ovdsat/data/rareplanes/rareplanes_coco_all-new.json"

with open(input_file, "r") as f:
    data = json.load(f)

before_annotations = len(data["annotations"])
before_categories = len(data["categories"])

# Remove annotations and category with ID 2
data["annotations"] = [
    annotation
    for annotation in data["annotations"]
    if int(annotation["category_id"]) != 2
]

data["categories"] = [
    category
    for category in data["categories"]
    if int(category["id"]) != 2
]

# Shift every category ID greater than 2 down by 1
for category in data["categories"]:
    if int(category["id"]) > 2:
        category["id"] = int(category["id"]) - 1

# Update annotation category IDs to match
for annotation in data["annotations"]:
    if int(annotation["category_id"]) > 2:
        annotation["category_id"] = int(annotation["category_id"]) - 1

data["categories"] = sorted(
    data["categories"],
    key=lambda category: int(category["id"])
)

with open(output_file, "w") as f:
    json.dump(data, f, indent=4)

print(f"Removed {before_annotations - len(data['annotations'])} annotations")
print(f"Removed {before_categories - len(data['categories'])} categories")
print(f"Saved to {output_file}")

Removed 10 annotations
Removed 1 categories
Saved to /home/gridsan/manderson/ovdsat/data/rareplanes/rareplanes_coco_all-new.json

#### Checks

In [28]:
import json
from collections import Counter

json_file = "/home/gridsan/manderson/ovdsat/data/rareplanes/val_coco-3.json"

with open(json_file, "r") as f:
    data = json.load(f)

counts = Counter(
    annotation["category_id"]
    for annotation in data["annotations"]
)

category_names = {
    category["id"]: category["name"]
    for category in data.get("categories", [])
}

for category_id in sorted(counts):
    category_name = category_names.get(category_id, "Unknown")
    print(f"{category_id}: {category_name} = {counts[category_id]} annotations")

0: Large Civil Transport/Utility = 2175 annotations
1: Medium Civil Transport/Utility = 8001 annotations
2: Military Fighter/Interceptor/Attack = 221 annotations
3: Military Trainer = 16 annotations
4: Military Transport/Utility/AWAC = 444 annotations
5: Small Civil Transport/Utility = 11481 annotations

0: Large Civil Transport/Utility = 2112 annotations
1: Medium Civil Transport/Utility = 7964 annotations
3: Military Fighter/Interceptor/Attack = 105 annotations
5: Military Transport/Utility/AWAC = 376 annotations
6: Small Civil Transport/Utility = 11259 annotations

Large Civil Transport/Utility        512        170      0.393      0.194      0.274      0.134
Medium Civil Transport/Utility        512        542          1    0.00185      0.501      0.301
Military Transport/Utility/AWAC        512          6          0          0          0          0

In [4]:
import json
from collections import Counter

json_file1 = "/home/gridsan/manderson/ovdsat/data/rareplanes/metadata_annotations/RarePlanes_Test_Coco_Annotations_tiled.json"
json_file2 = "/home/gridsan/manderson/ovdsat/data/rareplanes/metadata_annotations/RarePlanes_Train_Coco_Annotations_tiled.json"

role_counts = Counter()

for json_file in [json_file1, json_file2]:
    with open(json_file, "r") as f:
        data = json.load(f)

    role_counts.update(
        annotation["role"]
        for annotation in data["annotations"]
        if "role" in annotation
    )

for role, count in sorted(role_counts.items()):
    print(f"{role}: {count}")

missing = 0

for json_file in [json_file1, json_file2]:
    with open(json_file, "r") as f:
        data = json.load(f)

    missing += sum(
        "role" not in annotation
        for annotation in data["annotations"]
    )

print(f"Missing role: {missing}")

Large Civil Transport/Utility: 2417
Medium Civil Transport/Utility: 8997
Military Bomber: 10
Military Fighter/Interceptor/Attack: 296
Military Trainer: 27
Military Transport/Utility/AWAC: 514
Small Civil Transport/Utility: 12944
Missing role: 0

### Generate splits for few shot, finetune, and validation

In [5]:
# Load your COCO dataset
coco_json = f"/home/gridsan/manderson/ovdsat/data/rareplanes/rareplanes_coco_all.json"
path_to_images = "/home/gridsan/manderson/ovdsat/data/dior/PNGImages"   # folder with your images

all_dataset = importer.ImportCoco(
    path=coco_json,
    path_to_images=path_to_images,
    name="RarePlanes"
)

# Get the dataframe
df = all_dataset.df
print(len(df))
df.head()

25197

/home/gridsan/manderson/.conda/envs/test/lib/python3.9/site-packages/pylabel/importer.py:127: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.fillna("", inplace=True)

,img_folder,img_filename,img_path,img_id,img_width,img_height,img_depth,ann_segmented,ann_bbox_xmin,ann_bbox_ymin,...,ann_iscrowd,ann_keypoints,ann_pose,ann_truncated,ann_difficult,cat_id,cat_name,cat_supercategory,split,annotated
id,,,,,,,,,,,,,,,,,,,,,
0,/home/gridsan/manderson/ovdsat/data/dior/PNGIm...,67_104001003F0B3200_tile_644.png,,1,512,512,3,1,0.0,177.133463,...,0.0,,Unspecified,1.0,,0,Large Civil Transport/Utility,aircraft,,1
1,/home/gridsan/manderson/ovdsat/data/dior/PNGIm...,67_104001003F0B3200_tile_644.png,,1,512,512,3,1,225.330706,238.940418,...,0.0,,Unspecified,0.0,,1,Medium Civil Transport/Utility,aircraft,,1
2,/home/gridsan/manderson/ovdsat/data/dior/PNGIm...,69_104005000CDBE200_tile_3501.png,,2,512,512,3,1,137.342232,0.0,...,0.0,,Unspecified,1.0,,0,Large Civil Transport/Utility,aircraft,,1
3,/home/gridsan/manderson/ovdsat/data/dior/PNGIm...,96_104001003C8C7800_tile_1132.png,,3,512,512,3,1,0.329081,443.142902,...,0.0,,Unspecified,0.0,,5,Small Civil Transport/Utility,aircraft,,1
4,/home/gridsan/manderson/ovdsat/data/dior/PNGIm...,96_104001003C8C7800_tile_1132.png,,3,512,512,3,1,69.492566,498.334967,...,0.0,,Unspecified,1.0,,5,Small Civil Transport/Utility,aircraft,,1

In [8]:
save_dir = '/home/gridsan/manderson/ovdsat/data/rareplanes'

for M in [1, 2, 3]:
    img_ids = set()
    prev_samples = {}  # track selected samples per category
    
    for N in [1, 3, 5, 10, 30]:
        train_file = f'{save_dir}/train_coco_subset_N{N}-{M}.json'
        val_file = f'{save_dir}/val_coco-{M}.json'
        finetune_val_file = f'{save_dir}/train_coco_finetune_val-{M}.json'
        
        N_samples_list = []

        for value, group in df.groupby('cat_id'):
            #print(f"cat_id = {value}")
            # start with previous samples for this category, if any
            prev_df = prev_samples.get(value, pd.DataFrame(columns=group.columns))
            pool = group.loc[~group['img_id'].isin(prev_df['img_id'])]

            # number of new samples to add for this N
            needed = max(0, N - len(prev_df))
            pool = group.loc[~group['img_id'].isin(prev_df['img_id'])]
            take = min(needed, len(pool))
            if take < needed:
                print(f'Warning: for cat id {value}, N={N}, M={M}, there are only {take} images left to sample from!')
            
            # print(
            #     f"cat_id={value} | "
            #     f"group={len(group)} | "
            #     f"prev={len(prev_df)} | "
            #     f"needed={needed} | "
            #     f"remaining img pool={len(pool)}"
            # )
            
            if take > 0:
                # new_samples = group.loc[~group['img_id'].isin(prev_df['img_id'])].sample(
                #     n=min(needed, len(group) - len(prev_df)), replace=False
                # )
                # current_df = pd.concat([prev_df, new_samples], ignore_index=True)
                new_samples = pool.sample(n=take, replace=False)
                current_df = pd.concat([prev_df, new_samples], ignore_index=True)
            else:
                current_df = prev_df

            # save for next round
            prev_samples[value] = current_df
            N_samples_list.append(current_df)
            img_ids.update(current_df['img_id'].tolist())

        print(f"M={M}, N={N}, total unique imgs={len(img_ids)}")

        # combine and export
        N_samples_df = pd.concat(N_samples_list, ignore_index=True).reset_index(drop=True)
        pylabel_df_N = dataset.Dataset(N_samples_df)
        exp = exporter.Export(pylabel_df_N)
        exp.ExportToCoco(output_path=train_file, cat_id_index=0)

        with open(train_file, 'r') as f:
            train_data = json.load(f)
        train_data['categories'] = sorted(train_data['categories'], key=lambda x: x['id'])
        with open(f'{train_file[:-5]}.json', 'w') as f:
            json.dump(train_data, f, indent=4)
        print(f'Saved {train_file[:-5]}.json')

    # Remaining images (not in any N-shot)
    remaining_df = df[~df['img_id'].isin(img_ids)]
    remaining_img_ids = remaining_df['img_id'].unique()

    # Split into validation and finetune sets
    ft_percent = 0.1
    val_ids, ft_ids = train_test_split(remaining_img_ids, test_size=ft_percent)

    # --- Validation set ---
    val_df = df[df['img_id'].isin(val_ids)].reset_index(drop=True)
    exp = exporter.Export(dataset.Dataset(val_df))
    exp.ExportToCoco(output_path=val_file, cat_id_index=0)

    # --- Finetune validation set ---
    ft_df = df[df['img_id'].isin(ft_ids)].reset_index(drop=True)
    exp = exporter.Export(dataset.Dataset(ft_df))
    exp.ExportToCoco(output_path=finetune_val_file, cat_id_index=0)

    # Sort categories in both
    for fpath in [finetune_val_file, val_file]:
        with open(fpath, 'r') as f:
            data = json.load(f)
        data['categories'] = sorted(data['categories'], key=lambda x: x['id'])
        with open(f'{fpath[:-5]}.json', 'w') as f:
            json.dump(data, f, indent=4)
        print(f'Saved {fpath[:-5]}.json')

/state/partition1/slurm_tmp/5160845.0.0/ipykernel_231771/4079074005.py:41: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  current_df = pd.concat([prev_df, new_samples], ignore_index=True)
/state/partition1/slurm_tmp/5160845.0.0/ipykernel_231771/4079074005.py:41: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  current_df = pd.concat([prev_df, new_samples], ignore_index=True)
/state/partition1/slurm_tmp/5160845.0.0/ipykernel_231771/4079074005.py:41: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  current_df = pd.concat([prev_df, new_samples], ignore_index=True)
/state/partition1/slurm_tmp/5160845.0.0/ipykernel_231771/4079074005.py:41: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  current_df = pd.concat([prev_df, new_samples], ignore_index=True)
/state/partition1/slurm_tmp/5160845.0.0/ipykernel_231771/4079074005.py:41: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  current_df = pd.concat([prev_df, new_samples], ignore_index=True)
/state/partition1/slurm_tmp/5160845.0.0/ipykernel_231771/4079074005.py:41: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  current_df = pd.concat([prev_df, new_samples], ignore_index=True)
/state/partition1/slurm_tmp/5160845.0.0/ipykernel_231771/4079074005.py:41: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  current_df = pd.concat([prev_df, new_samples], ignore_index=True)
/home/gridsan/manderson/.conda/envs/test/lib/python3.9/site-packages/pylabel/exporter.py:767: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace(r"^\s*$", np.nan, regex=True)

M=1, N=1, total unique imgs=7

Exporting to COCO file...: 100%|██████████| 7/7 [00:00<00:00, 71.91it/s]
/home/gridsan/manderson/.conda/envs/test/lib/python3.9/site-packages/pylabel/exporter.py:767: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace(r"^\s*$", np.nan, regex=True)

Saved /home/gridsan/manderson/ovdsat/data/rareplanes/train_coco_subset_N1-1.json
M=1, N=3, total unique imgs=21

Exporting to COCO file...: 100%|██████████| 21/21 [00:00<00:00, 766.41it/s]
/home/gridsan/manderson/.conda/envs/test/lib/python3.9/site-packages/pylabel/exporter.py:767: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace(r"^\s*$", np.nan, regex=True)

Saved /home/gridsan/manderson/ovdsat/data/rareplanes/train_coco_subset_N3-1.json
M=1, N=5, total unique imgs=34

Exporting to COCO file...: 100%|██████████| 35/35 [00:00<00:00, 1013.91it/s]
/home/gridsan/manderson/.conda/envs/test/lib/python3.9/site-packages/pylabel/exporter.py:767: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace(r"^\s*$", np.nan, regex=True)

Saved /home/gridsan/manderson/ovdsat/data/rareplanes/train_coco_subset_N5-1.json
M=1, N=10, total unique imgs=64

Exporting to COCO file...: 100%|██████████| 70/70 [00:00<00:00, 840.89it/s]
/home/gridsan/manderson/.conda/envs/test/lib/python3.9/site-packages/pylabel/exporter.py:767: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace(r"^\s*$", np.nan, regex=True)

Saved /home/gridsan/manderson/ovdsat/data/rareplanes/train_coco_subset_N10-1.json
Warning: for cat id 2, N=30, M=1, there are only 0 images left to sample from!
Warning: for cat id 4, N=30, M=1, there are only 13 images left to sample from!
M=1, N=30, total unique imgs=167

Exporting to COCO file...: 100%|██████████| 183/183 [00:00<00:00, 2134.49it/s]

Saved /home/gridsan/manderson/ovdsat/data/rareplanes/train_coco_subset_N30-1.json

Exporting to COCO file...: 100%|██████████| 21927/21927 [00:12<00:00, 1702.99it/s]
Exporting to COCO file...: 100%|██████████| 2374/2374 [00:01<00:00, 2237.34it/s]

Saved /home/gridsan/manderson/ovdsat/data/rareplanes/train_coco_finetune_val-1.json

/state/partition1/slurm_tmp/5160845.0.0/ipykernel_231771/4079074005.py:41: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  current_df = pd.concat([prev_df, new_samples], ignore_index=True)
/state/partition1/slurm_tmp/5160845.0.0/ipykernel_231771/4079074005.py:41: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  current_df = pd.concat([prev_df, new_samples], ignore_index=True)
/state/partition1/slurm_tmp/5160845.0.0/ipykernel_231771/4079074005.py:41: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  current_df = pd.concat([prev_df, new_samples], ignore_index=True)
/state/partition1/slurm_tmp/5160845.0.0/ipykernel_231771/4079074005.py:41: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  current_df = pd.concat([prev_df, new_samples], ignore_index=True)
/state/partition1/slurm_tmp/5160845.0.0/ipykernel_231771/4079074005.py:41: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  current_df = pd.concat([prev_df, new_samples], ignore_index=True)
/state/partition1/slurm_tmp/5160845.0.0/ipykernel_231771/4079074005.py:41: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  current_df = pd.concat([prev_df, new_samples], ignore_index=True)
/state/partition1/slurm_tmp/5160845.0.0/ipykernel_231771/4079074005.py:41: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  current_df = pd.concat([prev_df, new_samples], ignore_index=True)
/home/gridsan/manderson/.conda/envs/test/lib/python3.9/site-packages/pylabel/exporter.py:767: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace(r"^\s*$", np.nan, regex=True)

Saved /home/gridsan/manderson/ovdsat/data/rareplanes/val_coco-1.json
M=2, N=1, total unique imgs=7

Exporting to COCO file...: 100%|██████████| 7/7 [00:00<00:00, 291.63it/s]
/home/gridsan/manderson/.conda/envs/test/lib/python3.9/site-packages/pylabel/exporter.py:767: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace(r"^\s*$", np.nan, regex=True)

Saved /home/gridsan/manderson/ovdsat/data/rareplanes/train_coco_subset_N1-2.json
M=2, N=3, total unique imgs=20

Exporting to COCO file...: 100%|██████████| 21/21 [00:00<00:00, 773.16it/s]
/home/gridsan/manderson/.conda/envs/test/lib/python3.9/site-packages/pylabel/exporter.py:767: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace(r"^\s*$", np.nan, regex=True)

Saved /home/gridsan/manderson/ovdsat/data/rareplanes/train_coco_subset_N3-2.json
M=2, N=5, total unique imgs=34

Exporting to COCO file...: 100%|██████████| 35/35 [00:00<00:00, 757.49it/s]
/home/gridsan/manderson/.conda/envs/test/lib/python3.9/site-packages/pylabel/exporter.py:767: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace(r"^\s*$", np.nan, regex=True)

Saved /home/gridsan/manderson/ovdsat/data/rareplanes/train_coco_subset_N5-2.json
M=2, N=10, total unique imgs=66

Exporting to COCO file...: 100%|██████████| 70/70 [00:00<00:00, 1750.99it/s]

Saved /home/gridsan/manderson/ovdsat/data/rareplanes/train_coco_subset_N10-2.json
Warning: for cat id 2, N=30, M=2, there are only 0 images left to sample from!
Warning: for cat id 4, N=30, M=2, there are only 14 images left to sample from!

/home/gridsan/manderson/.conda/envs/test/lib/python3.9/site-packages/pylabel/exporter.py:767: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace(r"^\s*$", np.nan, regex=True)

M=2, N=30, total unique imgs=166

Exporting to COCO file...: 100%|██████████| 184/184 [00:00<00:00, 2384.24it/s]

Saved /home/gridsan/manderson/ovdsat/data/rareplanes/train_coco_subset_N30-2.json

Exporting to COCO file...: 100%|██████████| 21875/21875 [00:12<00:00, 1692.23it/s]
Exporting to COCO file...: 100%|██████████| 2431/2431 [00:00<00:00, 3472.35it/s]

Saved /home/gridsan/manderson/ovdsat/data/rareplanes/train_coco_finetune_val-2.json

/state/partition1/slurm_tmp/5160845.0.0/ipykernel_231771/4079074005.py:41: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  current_df = pd.concat([prev_df, new_samples], ignore_index=True)
/state/partition1/slurm_tmp/5160845.0.0/ipykernel_231771/4079074005.py:41: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  current_df = pd.concat([prev_df, new_samples], ignore_index=True)
/state/partition1/slurm_tmp/5160845.0.0/ipykernel_231771/4079074005.py:41: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  current_df = pd.concat([prev_df, new_samples], ignore_index=True)
/state/partition1/slurm_tmp/5160845.0.0/ipykernel_231771/4079074005.py:41: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  current_df = pd.concat([prev_df, new_samples], ignore_index=True)
/state/partition1/slurm_tmp/5160845.0.0/ipykernel_231771/4079074005.py:41: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  current_df = pd.concat([prev_df, new_samples], ignore_index=True)
/state/partition1/slurm_tmp/5160845.0.0/ipykernel_231771/4079074005.py:41: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  current_df = pd.concat([prev_df, new_samples], ignore_index=True)
/state/partition1/slurm_tmp/5160845.0.0/ipykernel_231771/4079074005.py:41: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  current_df = pd.concat([prev_df, new_samples], ignore_index=True)
/home/gridsan/manderson/.conda/envs/test/lib/python3.9/site-packages/pylabel/exporter.py:767: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace(r"^\s*$", np.nan, regex=True)

Saved /home/gridsan/manderson/ovdsat/data/rareplanes/val_coco-2.json
M=3, N=1, total unique imgs=7

Exporting to COCO file...: 100%|██████████| 7/7 [00:00<00:00, 333.70it/s]
/home/gridsan/manderson/.conda/envs/test/lib/python3.9/site-packages/pylabel/exporter.py:767: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace(r"^\s*$", np.nan, regex=True)

Saved /home/gridsan/manderson/ovdsat/data/rareplanes/train_coco_subset_N1-3.json
M=3, N=3, total unique imgs=21

Exporting to COCO file...: 100%|██████████| 21/21 [00:00<00:00, 677.69it/s]
/home/gridsan/manderson/.conda/envs/test/lib/python3.9/site-packages/pylabel/exporter.py:767: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace(r"^\s*$", np.nan, regex=True)

Saved /home/gridsan/manderson/ovdsat/data/rareplanes/train_coco_subset_N3-3.json
M=3, N=5, total unique imgs=34

Exporting to COCO file...: 100%|██████████| 35/35 [00:00<00:00, 1226.65it/s]
/home/gridsan/manderson/.conda/envs/test/lib/python3.9/site-packages/pylabel/exporter.py:767: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace(r"^\s*$", np.nan, regex=True)

Saved /home/gridsan/manderson/ovdsat/data/rareplanes/train_coco_subset_N5-3.json
M=3, N=10, total unique imgs=67

Exporting to COCO file...: 100%|██████████| 70/70 [00:00<00:00, 1497.34it/s]

Saved /home/gridsan/manderson/ovdsat/data/rareplanes/train_coco_subset_N10-3.json
Warning: for cat id 2, N=30, M=3, there are only 0 images left to sample from!
Warning: for cat id 4, N=30, M=3, there are only 15 images left to sample from!
M=3, N=30, total unique imgs=168

/home/gridsan/manderson/.conda/envs/test/lib/python3.9/site-packages/pylabel/exporter.py:767: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace(r"^\s*$", np.nan, regex=True)
Exporting to COCO file...: 100%|██████████| 185/185 [00:00<00:00, 425.99it/s]

Saved /home/gridsan/manderson/ovdsat/data/rareplanes/train_coco_subset_N30-3.json

Exporting to COCO file...: 100%|██████████| 21903/21903 [00:12<00:00, 1753.15it/s]
Exporting to COCO file...: 100%|██████████| 2456/2456 [00:01<00:00, 2205.24it/s]

Saved /home/gridsan/manderson/ovdsat/data/rareplanes/train_coco_finetune_val-3.json
Saved /home/gridsan/manderson/ovdsat/data/rareplanes/val_coco-3.json

In [9]:
import json
from collections import defaultdict, deque, Counter

import pandas as pd
from sklearn.model_selection import train_test_split


# Load original COCO JSON so additional annotation metadata is preserved
with open(coco_json, "r") as f:
    original_coco = json.load(f)


# Match dataframe annotation rows to original COCO annotations using image + bbox
annotation_lookup = defaultdict(deque)

for ann in original_coco["annotations"]:
    x, y, w, h = ann["bbox"]
    key = (
        int(ann["image_id"]),
        round(float(x), 6),
        round(float(y), 6),
        round(float(w), 6),
        round(float(h), 6),
    )
    annotation_lookup[key].append(int(ann["id"]))


df = df.copy()
df["_original_ann_id"] = None

for index, row in df.iterrows():
    # Skip image-only rows with no annotation/category
    if pd.isna(row["cat_id"]) or str(row["cat_id"]).strip() == "":
        continue

    key = (
        int(row["img_id"]),
        round(float(row["ann_bbox_xmin"]), 6),
        round(float(row["ann_bbox_ymin"]), 6),
        round(float(row["ann_bbox_width"]), 6),
        round(float(row["ann_bbox_height"]), 6),
    )

    if not annotation_lookup[key]:
        raise ValueError(
            f"Could not match row {index}: "
            f"img_id={row['img_id']}, "
            f"bbox={[row['ann_bbox_xmin'], row['ann_bbox_ymin'], row['ann_bbox_width'], row['ann_bbox_height']]}"
        )

    df.at[index, "_original_ann_id"] = annotation_lookup[key].popleft()


def save_annotation_subset(selected_df, output_file):
    """Save only the exact selected annotations."""
    ann_ids = {
        int(x)
        for x in selected_df["_original_ann_id"]
        if pd.notna(x)
    }

    annotations = [
        ann for ann in original_coco["annotations"]
        if int(ann["id"]) in ann_ids
    ]

    image_ids = {int(ann["image_id"]) for ann in annotations}

    images = [
        image for image in original_coco["images"]
        if int(image["id"]) in image_ids
    ]

    data = {
        key: value
        for key, value in original_coco.items()
        if key not in {"images", "annotations", "categories"}
    }

    data["images"] = images
    data["annotations"] = annotations
    data["categories"] = sorted(
        original_coco["categories"],
        key=lambda x: int(x["id"])
    )

    with open(output_file, "w") as f:
        json.dump(data, f, indent=4)

    print(f"Saved {output_file}")


def save_image_subset(image_ids, output_file):
    """Save selected images and all annotations belonging to them."""
    image_ids = {int(x) for x in image_ids}

    images = [
        image for image in original_coco["images"]
        if int(image["id"]) in image_ids
    ]

    annotations = [
        ann for ann in original_coco["annotations"]
        if int(ann["image_id"]) in image_ids
    ]

    data = {
        key: value
        for key, value in original_coco.items()
        if key not in {"images", "annotations", "categories"}
    }

    data["images"] = images
    data["annotations"] = annotations
    data["categories"] = sorted(
        original_coco["categories"],
        key=lambda x: int(x["id"])
    )

    with open(output_file, "w") as f:
        json.dump(data, f, indent=4)

    print(f"Saved {output_file}")


def check_n_shot(output_file, N):
    with open(output_file, "r") as f:
        data = json.load(f)

    counts = Counter(
        int(ann["category_id"])
        for ann in data["annotations"]
    )

    expected_categories = {
        int(category_id)
        for category_id in df.loc[
            df["_original_ann_id"].notna(), "cat_id"
        ].unique()
    }

    wrong = {
        category_id: counts.get(category_id, 0)
        for category_id in expected_categories
        if counts.get(category_id, 0) != N
    }

    assert not wrong, (
        f"{output_file} does not have exactly {N} annotations per class: "
        f"{wrong}"
    )

    assert len(data["annotations"]) == N * len(expected_categories)

    print(
        f"CHECK PASSED: {N} annotations per class, "
        f"{len(data['annotations'])} total annotations"
    )


save_dir = "/home/gridsan/manderson/ovdsat/data/rareplanes"

for M in [1, 2, 3]:
    img_ids = set()
    prev_samples = {}

    for N in [1, 5, 10]:
        train_file = f"{save_dir}/train_coco_subset_N{N}-{M}.json"
        val_file = f"{save_dir}/val_coco-{M}.json"
        finetune_val_file = f"{save_dir}/train_coco_finetune_val-{M}.json"

        N_samples_list = []

        # Ignore image-only rows with blank cat_id
        annotated_df = df[df["_original_ann_id"].notna()]

        for value, group in annotated_df.groupby("cat_id"):
            prev_df = prev_samples.get(
                value,
                pd.DataFrame(columns=group.columns)
            )

            pool = group.loc[
                ~group["img_id"].isin(prev_df["img_id"])
            ]

            needed = max(0, N - len(prev_df))
            take = min(needed, len(pool))

            if take < needed:
                print(
                    f"Warning: for cat id {value}, N={N}, M={M}, "
                    f"there are only {take} images left to sample from!"
                )

            if take > 0:
                new_samples = pool.sample(n=take, replace=False)
                current_df = pd.concat(
                    [prev_df, new_samples],
                    ignore_index=True
                )
            else:
                current_df = prev_df

            prev_samples[value] = current_df
            N_samples_list.append(current_df)
            img_ids.update(current_df["img_id"].tolist())

        print(f"M={M}, N={N}, total unique imgs={len(img_ids)}")

        N_samples_df = pd.concat(
            N_samples_list,
            ignore_index=True
        ).reset_index(drop=True)

        save_annotation_subset(N_samples_df, train_file)
        check_n_shot(train_file, N)

    # Remaining images not used in any N-shot subset
    remaining_df = df[~df["img_id"].isin(img_ids)]
    remaining_img_ids = remaining_df["img_id"].unique()

    ft_percent = 0.1
    val_ids, ft_ids = train_test_split(
        remaining_img_ids,
        test_size=ft_percent
    )

    save_image_subset(val_ids, val_file)
    save_image_subset(ft_ids, finetune_val_file)

M=1, N=1, total unique imgs=6
Saved /home/gridsan/manderson/ovdsat/data/rareplanes/train_coco_subset_N1-1.json
CHECK PASSED: 1 annotations per class, 6 total annotations
M=1, N=5, total unique imgs=30
Saved /home/gridsan/manderson/ovdsat/data/rareplanes/train_coco_subset_N5-1.json
CHECK PASSED: 5 annotations per class, 30 total annotations
M=1, N=10, total unique imgs=60
Saved /home/gridsan/manderson/ovdsat/data/rareplanes/train_coco_subset_N10-1.json
CHECK PASSED: 10 annotations per class, 60 total annotations
Saved /home/gridsan/manderson/ovdsat/data/rareplanes/val_coco-1.json
Saved /home/gridsan/manderson/ovdsat/data/rareplanes/train_coco_finetune_val-1.json
M=2, N=1, total unique imgs=6
Saved /home/gridsan/manderson/ovdsat/data/rareplanes/train_coco_subset_N1-2.json
CHECK PASSED: 1 annotations per class, 6 total annotations
M=2, N=5, total unique imgs=29
Saved /home/gridsan/manderson/ovdsat/data/rareplanes/train_coco_subset_N5-2.json
CHECK PASSED: 5 annotations per class, 30 total annotations
M=2, N=10, total unique imgs=59
Saved /home/gridsan/manderson/ovdsat/data/rareplanes/train_coco_subset_N10-2.json
CHECK PASSED: 10 annotations per class, 60 total annotations
Saved /home/gridsan/manderson/ovdsat/data/rareplanes/val_coco-2.json
Saved /home/gridsan/manderson/ovdsat/data/rareplanes/train_coco_finetune_val-2.json
M=3, N=1, total unique imgs=6
Saved /home/gridsan/manderson/ovdsat/data/rareplanes/train_coco_subset_N1-3.json
CHECK PASSED: 1 annotations per class, 6 total annotations
M=3, N=5, total unique imgs=30
Saved /home/gridsan/manderson/ovdsat/data/rareplanes/train_coco_subset_N5-3.json
CHECK PASSED: 5 annotations per class, 30 total annotations
M=3, N=10, total unique imgs=59
Saved /home/gridsan/manderson/ovdsat/data/rareplanes/train_coco_subset_N10-3.json
CHECK PASSED: 10 annotations per class, 60 total annotations
Saved /home/gridsan/manderson/ovdsat/data/rareplanes/val_coco-3.json
Saved /home/gridsan/manderson/ovdsat/data/rareplanes/train_coco_finetune_val-3.json

### Extras

In [5]:
### Sanity check for N=100

save_dir = '/home/gridsan/manderson/ovdsat/data/dior'

for M in [1, 2, 3]:
    img_ids = set()
    prev_samples = {}  # track selected samples per category
    
    for N in [100]:
        train_file = f'{save_dir}/train_coco_subset_N{N}-{M}.json'
        val_file = f'{save_dir}/val_coco_N{N}-{M}.json'
        finetune_val_file = f'{save_dir}/train_coco_finetune_val_N{N}-{M}.json'
        
        N_samples_list = []

        for value, group in df.groupby('cat_id'):
            # start with previous samples for this category, if any
            prev_df = prev_samples.get(value, pd.DataFrame(columns=group.columns))

            # number of new samples to add for this N
            needed = max(0, N - len(prev_df))
            if needed > 0:
                new_samples = group.loc[~group['img_id'].isin(prev_df['img_id'])].sample(
                    n=min(needed, len(group) - len(prev_df)), replace=False
                )
                current_df = pd.concat([prev_df, new_samples], ignore_index=True)
            else:
                current_df = prev_df

            # save for next round
            prev_samples[value] = current_df
            N_samples_list.append(current_df)
            img_ids.update(current_df['img_id'].tolist())

        print(f"M={M}, N={N}, total unique imgs={len(img_ids)}")

        # combine and export
        N_samples_df = pd.concat(N_samples_list, ignore_index=True).reset_index(drop=True)
        pylabel_df_N = dataset.Dataset(N_samples_df)
        exp = exporter.Export(pylabel_df_N)
        exp.ExportToCoco(output_path=train_file, cat_id_index=0)

        with open(train_file, 'r') as f:
            train_data = json.load(f)
        train_data['categories'] = sorted(train_data['categories'], key=lambda x: x['id'])
        with open(f'{train_file[:-5]}.json', 'w') as f:
            json.dump(train_data, f, indent=4)
        print(f'Saved {train_file[:-5]}.json')

    # Remaining images (not in any N-shot)
    remaining_df = df[~df['img_id'].isin(img_ids)]
    remaining_img_ids = remaining_df['img_id'].unique()

    # Split into validation and finetune sets
    ft_percent = 0.1
    val_ids, ft_ids = train_test_split(remaining_img_ids, test_size=ft_percent)

    # --- Validation set ---
    val_df = df[df['img_id'].isin(val_ids)].reset_index(drop=True)
    exp = exporter.Export(dataset.Dataset(val_df))
    exp.ExportToCoco(output_path=val_file, cat_id_index=0)

    # --- Finetune validation set ---
    ft_df = df[df['img_id'].isin(ft_ids)].reset_index(drop=True)
    exp = exporter.Export(dataset.Dataset(ft_df))
    exp.ExportToCoco(output_path=finetune_val_file, cat_id_index=0)

    # Sort categories in both
    for fpath in [finetune_val_file, val_file]:
        with open(fpath, 'r') as f:
            data = json.load(f)
        data['categories'] = sorted(data['categories'], key=lambda x: x['id'])
        with open(f'{fpath[:-5]}.json', 'w') as f:
            json.dump(data, f, indent=4)
        print(f'Saved {fpath[:-5]}.json')

/state/partition1/slurm_tmp/3935540.0.0/ipykernel_2065714/2750094772.py:26: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  current_df = pd.concat([prev_df, new_samples], ignore_index=True)
/state/partition1/slurm_tmp/3935540.0.0/ipykernel_2065714/2750094772.py:26: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  current_df = pd.concat([prev_df, new_samples], ignore_index=True)
/state/partition1/slurm_tmp/3935540.0.0/ipykernel_2065714/2750094772.py:26: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  current_df = pd.concat([prev_df, new_samples], ignore_index=True)
/state/partition1/slurm_tmp/3935540.0.0/ipykernel_2065714/2750094772.py:26: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  current_df = pd.concat([prev_df, new_samples], ignore_index=True)
/state/partition1/slurm_tmp/3935540.0.0/ipykernel_2065714/2750094772.py:26: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  current_df = pd.concat([prev_df, new_samples], ignore_index=True)
/state/partition1/slurm_tmp/3935540.0.0/ipykernel_2065714/2750094772.py:26: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  current_df = pd.concat([prev_df, new_samples], ignore_index=True)
/state/partition1/slurm_tmp/3935540.0.0/ipykernel_2065714/2750094772.py:26: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  current_df = pd.concat([prev_df, new_samples], ignore_index=True)
/state/partition1/slurm_tmp/3935540.0.0/ipykernel_2065714/2750094772.py:26: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  current_df = pd.concat([prev_df, new_samples], ignore_index=True)
/state/partition1/slurm_tmp/3935540.0.0/ipykernel_2065714/2750094772.py:26: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  current_df = pd.concat([prev_df, new_samples], ignore_index=True)
/state/partition1/slurm_tmp/3935540.0.0/ipykernel_2065714/2750094772.py:26: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  current_df = pd.concat([prev_df, new_samples], ignore_index=True)
/state/partition1/slurm_tmp/3935540.0.0/ipykernel_2065714/2750094772.py:26: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  current_df = pd.concat([prev_df, new_samples], ignore_index=True)
/state/partition1/slurm_tmp/3935540.0.0/ipykernel_2065714/2750094772.py:26: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  current_df = pd.concat([prev_df, new_samples], ignore_index=True)
/state/partition1/slurm_tmp/3935540.0.0/ipykernel_2065714/2750094772.py:26: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  current_df = pd.concat([prev_df, new_samples], ignore_index=True)
/state/partition1/slurm_tmp/3935540.0.0/ipykernel_2065714/2750094772.py:26: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  current_df = pd.concat([prev_df, new_samples], ignore_index=True)
/state/partition1/slurm_tmp/3935540.0.0/ipykernel_2065714/2750094772.py:26: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  current_df = pd.concat([prev_df, new_samples], ignore_index=True)
/state/partition1/slurm_tmp/3935540.0.0/ipykernel_2065714/2750094772.py:26: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  current_df = pd.concat([prev_df, new_samples], ignore_index=True)
/state/partition1/slurm_tmp/3935540.0.0/ipykernel_2065714/2750094772.py:26: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  current_df = pd.concat([prev_df, new_samples], ignore_index=True)
/state/partition1/slurm_tmp/3935540.0.0/ipykernel_2065714/2750094772.py:26: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  current_df = pd.concat([prev_df, new_samples], ignore_index=True)
/state/partition1/slurm_tmp/3935540.0.0/ipykernel_2065714/2750094772.py:26: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  current_df = pd.concat([prev_df, new_samples], ignore_index=True)
/state/partition1/slurm_tmp/3935540.0.0/ipykernel_2065714/2750094772.py:26: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  current_df = pd.concat([prev_df, new_samples], ignore_index=True)
/home/gridsan/manderson/.conda/envs/test/lib/python3.9/site-packages/pylabel/exporter.py:767: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace(r"^\s*$", np.nan, regex=True)

M=1, N=100, total unique imgs=1916

Exporting to COCO file...: 100%|██████████| 2000/2000 [00:01<00:00, 1029.06it/s]

Saved /home/gridsan/manderson/ovdsat/data/dior/train_coco_subset_N100-1.json

Exporting to COCO file...: 100%|██████████| 29661/29661 [00:18<00:00, 1577.68it/s]
Exporting to COCO file...: 100%|██████████| 3238/3238 [00:01<00:00, 3194.98it/s]

Saved /home/gridsan/manderson/ovdsat/data/dior/train_coco_finetune_val_N100-1.json

/state/partition1/slurm_tmp/3935540.0.0/ipykernel_2065714/2750094772.py:26: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  current_df = pd.concat([prev_df, new_samples], ignore_index=True)
/state/partition1/slurm_tmp/3935540.0.0/ipykernel_2065714/2750094772.py:26: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  current_df = pd.concat([prev_df, new_samples], ignore_index=True)
/state/partition1/slurm_tmp/3935540.0.0/ipykernel_2065714/2750094772.py:26: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  current_df = pd.concat([prev_df, new_samples], ignore_index=True)
/state/partition1/slurm_tmp/3935540.0.0/ipykernel_2065714/2750094772.py:26: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  current_df = pd.concat([prev_df, new_samples], ignore_index=True)
/state/partition1/slurm_tmp/3935540.0.0/ipykernel_2065714/2750094772.py:26: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  current_df = pd.concat([prev_df, new_samples], ignore_index=True)
/state/partition1/slurm_tmp/3935540.0.0/ipykernel_2065714/2750094772.py:26: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  current_df = pd.concat([prev_df, new_samples], ignore_index=True)
/state/partition1/slurm_tmp/3935540.0.0/ipykernel_2065714/2750094772.py:26: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  current_df = pd.concat([prev_df, new_samples], ignore_index=True)
/state/partition1/slurm_tmp/3935540.0.0/ipykernel_2065714/2750094772.py:26: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  current_df = pd.concat([prev_df, new_samples], ignore_index=True)
/state/partition1/slurm_tmp/3935540.0.0/ipykernel_2065714/2750094772.py:26: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  current_df = pd.concat([prev_df, new_samples], ignore_index=True)
/state/partition1/slurm_tmp/3935540.0.0/ipykernel_2065714/2750094772.py:26: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  current_df = pd.concat([prev_df, new_samples], ignore_index=True)
/state/partition1/slurm_tmp/3935540.0.0/ipykernel_2065714/2750094772.py:26: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  current_df = pd.concat([prev_df, new_samples], ignore_index=True)
/state/partition1/slurm_tmp/3935540.0.0/ipykernel_2065714/2750094772.py:26: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  current_df = pd.concat([prev_df, new_samples], ignore_index=True)
/state/partition1/slurm_tmp/3935540.0.0/ipykernel_2065714/2750094772.py:26: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  current_df = pd.concat([prev_df, new_samples], ignore_index=True)
/state/partition1/slurm_tmp/3935540.0.0/ipykernel_2065714/2750094772.py:26: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  current_df = pd.concat([prev_df, new_samples], ignore_index=True)
/state/partition1/slurm_tmp/3935540.0.0/ipykernel_2065714/2750094772.py:26: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  current_df = pd.concat([prev_df, new_samples], ignore_index=True)
/state/partition1/slurm_tmp/3935540.0.0/ipykernel_2065714/2750094772.py:26: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  current_df = pd.concat([prev_df, new_samples], ignore_index=True)
/state/partition1/slurm_tmp/3935540.0.0/ipykernel_2065714/2750094772.py:26: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  current_df = pd.concat([prev_df, new_samples], ignore_index=True)
/state/partition1/slurm_tmp/3935540.0.0/ipykernel_2065714/2750094772.py:26: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  current_df = pd.concat([prev_df, new_samples], ignore_index=True)
/state/partition1/slurm_tmp/3935540.0.0/ipykernel_2065714/2750094772.py:26: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  current_df = pd.concat([prev_df, new_samples], ignore_index=True)
/state/partition1/slurm_tmp/3935540.0.0/ipykernel_2065714/2750094772.py:26: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  current_df = pd.concat([prev_df, new_samples], ignore_index=True)
/home/gridsan/manderson/.conda/envs/test/lib/python3.9/site-packages/pylabel/exporter.py:767: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace(r"^\s*$", np.nan, regex=True)

Saved /home/gridsan/manderson/ovdsat/data/dior/val_coco_N100-1.json
M=2, N=100, total unique imgs=1917

Exporting to COCO file...: 100%|██████████| 2000/2000 [00:00<00:00, 2575.23it/s]

Saved /home/gridsan/manderson/ovdsat/data/dior/train_coco_subset_N100-2.json

Exporting to COCO file...: 100%|██████████| 29869/29869 [00:18<00:00, 1597.16it/s]
Exporting to COCO file...: 100%|██████████| 3260/3260 [00:01<00:00, 2819.47it/s]

Saved /home/gridsan/manderson/ovdsat/data/dior/train_coco_finetune_val_N100-2.json

/state/partition1/slurm_tmp/3935540.0.0/ipykernel_2065714/2750094772.py:26: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  current_df = pd.concat([prev_df, new_samples], ignore_index=True)
/state/partition1/slurm_tmp/3935540.0.0/ipykernel_2065714/2750094772.py:26: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  current_df = pd.concat([prev_df, new_samples], ignore_index=True)
/state/partition1/slurm_tmp/3935540.0.0/ipykernel_2065714/2750094772.py:26: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  current_df = pd.concat([prev_df, new_samples], ignore_index=True)
/state/partition1/slurm_tmp/3935540.0.0/ipykernel_2065714/2750094772.py:26: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  current_df = pd.concat([prev_df, new_samples], ignore_index=True)
/state/partition1/slurm_tmp/3935540.0.0/ipykernel_2065714/2750094772.py:26: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  current_df = pd.concat([prev_df, new_samples], ignore_index=True)
/state/partition1/slurm_tmp/3935540.0.0/ipykernel_2065714/2750094772.py:26: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  current_df = pd.concat([prev_df, new_samples], ignore_index=True)
/state/partition1/slurm_tmp/3935540.0.0/ipykernel_2065714/2750094772.py:26: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  current_df = pd.concat([prev_df, new_samples], ignore_index=True)
/state/partition1/slurm_tmp/3935540.0.0/ipykernel_2065714/2750094772.py:26: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  current_df = pd.concat([prev_df, new_samples], ignore_index=True)
/state/partition1/slurm_tmp/3935540.0.0/ipykernel_2065714/2750094772.py:26: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  current_df = pd.concat([prev_df, new_samples], ignore_index=True)
/state/partition1/slurm_tmp/3935540.0.0/ipykernel_2065714/2750094772.py:26: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  current_df = pd.concat([prev_df, new_samples], ignore_index=True)
/state/partition1/slurm_tmp/3935540.0.0/ipykernel_2065714/2750094772.py:26: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  current_df = pd.concat([prev_df, new_samples], ignore_index=True)
/state/partition1/slurm_tmp/3935540.0.0/ipykernel_2065714/2750094772.py:26: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  current_df = pd.concat([prev_df, new_samples], ignore_index=True)
/state/partition1/slurm_tmp/3935540.0.0/ipykernel_2065714/2750094772.py:26: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  current_df = pd.concat([prev_df, new_samples], ignore_index=True)
/state/partition1/slurm_tmp/3935540.0.0/ipykernel_2065714/2750094772.py:26: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  current_df = pd.concat([prev_df, new_samples], ignore_index=True)
/state/partition1/slurm_tmp/3935540.0.0/ipykernel_2065714/2750094772.py:26: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  current_df = pd.concat([prev_df, new_samples], ignore_index=True)
/state/partition1/slurm_tmp/3935540.0.0/ipykernel_2065714/2750094772.py:26: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  current_df = pd.concat([prev_df, new_samples], ignore_index=True)
/state/partition1/slurm_tmp/3935540.0.0/ipykernel_2065714/2750094772.py:26: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  current_df = pd.concat([prev_df, new_samples], ignore_index=True)
/state/partition1/slurm_tmp/3935540.0.0/ipykernel_2065714/2750094772.py:26: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  current_df = pd.concat([prev_df, new_samples], ignore_index=True)
/state/partition1/slurm_tmp/3935540.0.0/ipykernel_2065714/2750094772.py:26: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  current_df = pd.concat([prev_df, new_samples], ignore_index=True)
/state/partition1/slurm_tmp/3935540.0.0/ipykernel_2065714/2750094772.py:26: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  current_df = pd.concat([prev_df, new_samples], ignore_index=True)
/home/gridsan/manderson/.conda/envs/test/lib/python3.9/site-packages/pylabel/exporter.py:767: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace(r"^\s*$", np.nan, regex=True)

Saved /home/gridsan/manderson/ovdsat/data/dior/val_coco_N100-2.json
M=3, N=100, total unique imgs=1909

Exporting to COCO file...: 100%|██████████| 2000/2000 [00:00<00:00, 2517.00it/s]

Saved /home/gridsan/manderson/ovdsat/data/dior/train_coco_subset_N100-3.json

Exporting to COCO file...: 100%|██████████| 29759/29759 [00:18<00:00, 1590.35it/s]
Exporting to COCO file...: 100%|██████████| 3244/3244 [00:00<00:00, 3300.66it/s]

Saved /home/gridsan/manderson/ovdsat/data/dior/train_coco_finetune_val_N100-3.json
Saved /home/gridsan/manderson/ovdsat/data/dior/val_coco_N100-3.json

In [3]:
import json
import random
from pathlib import Path

save_dir = Path("/home/gridsan/manderson/ovdsat/data/dior")

def extract_prefix(filename):
    return filename.split('_')[0]

def make_N20_from_N10_and_N30(M, save_dir=save_dir, seed=0):
    random.seed(seed)

    path_10 = save_dir / f"train_coco_subset_N10-{M}.json"
    path_30 = save_dir / f"train_coco_subset_N30-{M}.json"
    out_path = save_dir / f"train_coco_subset_N20-{M}.json"

    print(f"\n=== M={M}: building N=20 from {path_10.name} and {path_30.name} ===")

    with open(path_10, "r") as f:
        coco10 = json.load(f)
    with open(path_30, "r") as f:
        coco30 = json.load(f)

    # Map image_id → image metadata
    images_by_id = {img["id"]: img for img in coco30["images"]}
    for img in coco10["images"]:
        images_by_id.setdefault(img["id"], img)

    # Group annotations by category
    anns10_by_cat = {}
    anns30_by_cat = {}
    for ann in coco10["annotations"]:
        anns10_by_cat.setdefault(ann["category_id"], []).append(ann)
    for ann in coco30["annotations"]:
        anns30_by_cat.setdefault(ann["category_id"], []).append(ann)

    categories = sorted(coco30["categories"], key=lambda x: x["id"])
    final_annotations = []

    for cat in categories:
        cid = cat["id"]

        anns10 = anns10_by_cat.get(cid, [])
        anns30 = anns30_by_cat.get(cid, [])

        if len(anns10) != 10:
            raise ValueError(f"M={M}, category {cid}: N10 has {len(anns10)} anns (expected 10)")
        if len(anns30) < 30:
            raise ValueError(f"M={M}, category {cid}: N30 has {len(anns30)} anns (expected ≥30)")

        # Get prefixes used in N10
        used_prefixes = {
            extract_prefix(images_by_id[ann["image_id"]]["file_name"])
            for ann in anns10
        }

        # Filter N30 to exclude any with matching prefix
        eligible_from_30 = [
            ann for ann in anns30
            if extract_prefix(images_by_id[ann["image_id"]]["file_name"]) not in used_prefixes
        ]

        if len(eligible_from_30) < 10:
            raise ValueError(
                f"M={M}, category {cid}: only {len(eligible_from_30)} eligible anns after filtering by prefix"
            )

        extra = random.sample(eligible_from_30, 10)
        chosen = anns10 + extra
        final_annotations.extend(chosen)

    # Assign new unique annotation IDs
    new_annotations = []
    next_ann_id = 1
    for ann in final_annotations:
        ann_copy = dict(ann)
        ann_copy["id"] = next_ann_id
        new_annotations.append(ann_copy)
        next_ann_id += 1

    # Collect used images
    used_img_ids = {ann["image_id"] for ann in new_annotations}
    final_images = [images_by_id[iid] for iid in used_img_ids]

    coco20 = {
        "images": final_images,
        "annotations": new_annotations,
        "categories": categories,
    }

    for key in ("info", "licenses"):
        if key in coco30:
            coco20[key] = coco30[key]

    with open(out_path, "w") as f:
        json.dump(coco20, f, indent=4)

    print(f"[✓] wrote {out_path} — total annotations: {len(new_annotations)}")


# Run for all M
for M in [1, 2, 3, 4, 5]:
    make_N20_from_N10_and_N30(M)

=== M=1: building N=20 from train_coco_subset_N10-1.json and train_coco_subset_N30-1.json ===
[✓] wrote /home/gridsan/manderson/ovdsat/data/dior/train_coco_subset_N20-1.json — total annotations: 400

=== M=2: building N=20 from train_coco_subset_N10-2.json and train_coco_subset_N30-2.json ===
[✓] wrote /home/gridsan/manderson/ovdsat/data/dior/train_coco_subset_N20-2.json — total annotations: 400

=== M=3: building N=20 from train_coco_subset_N10-3.json and train_coco_subset_N30-3.json ===
[✓] wrote /home/gridsan/manderson/ovdsat/data/dior/train_coco_subset_N20-3.json — total annotations: 400

=== M=4: building N=20 from train_coco_subset_N10-4.json and train_coco_subset_N30-4.json ===
[✓] wrote /home/gridsan/manderson/ovdsat/data/dior/train_coco_subset_N20-4.json — total annotations: 400

=== M=5: building N=20 from train_coco_subset_N10-5.json and train_coco_subset_N30-5.json ===
[✓] wrote /home/gridsan/manderson/ovdsat/data/dior/train_coco_subset_N20-5.json — total annotations: 400

### Fix MAR20 names

In [1]:
import os
import json

In [3]:
CATEGORY_MAP = {
    "A1": "SU-35",
    "A2": "C-130",
    "A3": "C-17",
    "A4": "C-5",
    "A5": "F-16",
    "A6": "TU-160",
    "A7": "E-3",
    "A8": "B-52",
    "A9": "P-3C",
    "A10": "B-1B",
    "A11": "E-8",
    "A12": "TU-22",
    "A13": "F-15",
    "A14": "KC-135",
    "A15": "F-22",
    "A16": "FA-18",
    "A17": "TU-95",
    "A18": "KC-1",
    "A19": "SU-34",
    "A20": "SU-24",
}

def fix_category_names(json_dir):
    for fname in os.listdir(json_dir):
        if not fname.endswith(".json"):
            continue
        print(fname)

        path = os.path.join(json_dir, fname)

        with open(path, "r") as f:
            data = json.load(f)

        if "categories" not in data:
            print(f"[WARN] No categories in {fname}")
            continue

        changed = False
        for cat in data["categories"]:
            old_name = cat.get("name")
            if old_name in CATEGORY_MAP:
                cat["name"] = CATEGORY_MAP[old_name]
                changed = True

        if changed:
            with open(path, "w") as f:
                json.dump(data, f, indent=2)
            print(f"[OK] Updated {fname}")
        else:
            print(f"[SKIP] No changes in {fname}")

In [5]:
fix_category_names('mar')

[OK] Updated train_coco_subset_N3-3.json
[OK] Updated val_coco-3.json
[OK] Updated train_coco_finetune_val-1.json
[OK] Updated mar_coco_all.json
[OK] Updated train_coco_subset_N3-1.json
[OK] Updated train_coco_subset_N30-2.json
[OK] Updated train_coco_subset_N1-2.json
[OK] Updated train_coco_subset_N1-1.json
[OK] Updated val_coco-2.json
[OK] Updated train_coco_subset_N5-3.json
[OK] Updated train_coco_subset_N1-3.json
[OK] Updated train_coco_subset_N10-1.json
[OK] Updated val_coco-1.json
[OK] Updated train_coco_subset_N5-1.json
[OK] Updated train_coco_finetune_val-2.json
[OK] Updated train_coco_subset_N30-1.json
[OK] Updated train_coco_finetune_val-3.json
[OK] Updated train_coco_subset_N5-2.json
[OK] Updated train_coco_subset_N3-2.json
[OK] Updated train_coco_subset_N30-3.json
[OK] Updated train_coco_subset_N10-2.json
[OK] Updated train_coco_subset_N10-3.json

In [14]:
# Fix crop folder names
def rename_class_folders(root_dir, dry_run=False):
    """
    Recursively rename folders A1..A20 → aircraft names.

    Args:
        root_dir (str): Root directory to process
        dry_run (bool): If True, only print what would change
    """
    for dirpath, dirnames, _ in os.walk(root_dir, topdown=False):
        for d in dirnames:
            if d in CATEGORY_MAP:
                old_path = os.path.join(dirpath, d)
                new_path = os.path.join(dirpath, CATEGORY_MAP[d])

                if os.path.exists(new_path):
                    print(f"[SKIP] {new_path} already exists")
                    continue

                if dry_run:
                    print(f"[DRY-RUN] {old_path} → {new_path}")
                else:
                    os.rename(old_path, new_path)
                    print(f"[OK] {old_path} → {new_path}")

In [16]:
rename_class_folders('cropped_data/mar', dry_run=False)

[OK] cropped_data/mar/train/mar_N1-1/A2 → cropped_data/mar/train/mar_N1-1/C-130
[OK] cropped_data/mar/train/mar_N1-1/A14 → cropped_data/mar/train/mar_N1-1/KC-135
[OK] cropped_data/mar/train/mar_N1-1/A12 → cropped_data/mar/train/mar_N1-1/TU-22
[OK] cropped_data/mar/train/mar_N1-1/A9 → cropped_data/mar/train/mar_N1-1/P-3C
[OK] cropped_data/mar/train/mar_N1-1/A17 → cropped_data/mar/train/mar_N1-1/TU-95
[OK] cropped_data/mar/train/mar_N1-1/A20 → cropped_data/mar/train/mar_N1-1/SU-24
[OK] cropped_data/mar/train/mar_N1-1/A15 → cropped_data/mar/train/mar_N1-1/F-22
[OK] cropped_data/mar/train/mar_N1-1/A7 → cropped_data/mar/train/mar_N1-1/E-3
[OK] cropped_data/mar/train/mar_N1-1/A11 → cropped_data/mar/train/mar_N1-1/E-8
[OK] cropped_data/mar/train/mar_N1-1/A1 → cropped_data/mar/train/mar_N1-1/SU-35
[OK] cropped_data/mar/train/mar_N1-1/A6 → cropped_data/mar/train/mar_N1-1/TU-160
[OK] cropped_data/mar/train/mar_N1-1/A13 → cropped_data/mar/train/mar_N1-1/F-15
[OK] cropped_data/mar/train/mar_N1-1/A10 → cropped_data/mar/train/mar_N1-1/B-1B
[OK] cropped_data/mar/train/mar_N1-1/A4 → cropped_data/mar/train/mar_N1-1/C-5
[OK] cropped_data/mar/train/mar_N1-1/A19 → cropped_data/mar/train/mar_N1-1/SU-34
[OK] cropped_data/mar/train/mar_N1-1/A18 → cropped_data/mar/train/mar_N1-1/KC-1
[OK] cropped_data/mar/train/mar_N1-1/A16 → cropped_data/mar/train/mar_N1-1/FA-18
[OK] cropped_data/mar/train/mar_N1-1/A3 → cropped_data/mar/train/mar_N1-1/C-17
[OK] cropped_data/mar/train/mar_N1-1/A8 → cropped_data/mar/train/mar_N1-1/B-52
[OK] cropped_data/mar/train/mar_N1-1/A5 → cropped_data/mar/train/mar_N1-1/F-16
[OK] cropped_data/mar/train/mar_N3-3/A2 → cropped_data/mar/train/mar_N3-3/C-130
[OK] cropped_data/mar/train/mar_N3-3/A14 → cropped_data/mar/train/mar_N3-3/KC-135
[OK] cropped_data/mar/train/mar_N3-3/A12 → cropped_data/mar/train/mar_N3-3/TU-22
[OK] cropped_data/mar/train/mar_N3-3/A9 → cropped_data/mar/train/mar_N3-3/P-3C
[OK] cropped_data/mar/train/mar_N3-3/A17 → cropped_data/mar/train/mar_N3-3/TU-95
[OK] cropped_data/mar/train/mar_N3-3/A20 → cropped_data/mar/train/mar_N3-3/SU-24
[OK] cropped_data/mar/train/mar_N3-3/A15 → cropped_data/mar/train/mar_N3-3/F-22
[OK] cropped_data/mar/train/mar_N3-3/A7 → cropped_data/mar/train/mar_N3-3/E-3
[OK] cropped_data/mar/train/mar_N3-3/A11 → cropped_data/mar/train/mar_N3-3/E-8
[OK] cropped_data/mar/train/mar_N3-3/A1 → cropped_data/mar/train/mar_N3-3/SU-35
[OK] cropped_data/mar/train/mar_N3-3/A6 → cropped_data/mar/train/mar_N3-3/TU-160
[OK] cropped_data/mar/train/mar_N3-3/A13 → cropped_data/mar/train/mar_N3-3/F-15
[OK] cropped_data/mar/train/mar_N3-3/A10 → cropped_data/mar/train/mar_N3-3/B-1B
[OK] cropped_data/mar/train/mar_N3-3/A4 → cropped_data/mar/train/mar_N3-3/C-5
[OK] cropped_data/mar/train/mar_N3-3/A19 → cropped_data/mar/train/mar_N3-3/SU-34
[OK] cropped_data/mar/train/mar_N3-3/A18 → cropped_data/mar/train/mar_N3-3/KC-1
[OK] cropped_data/mar/train/mar_N3-3/A16 → cropped_data/mar/train/mar_N3-3/FA-18
[OK] cropped_data/mar/train/mar_N3-3/A3 → cropped_data/mar/train/mar_N3-3/C-17
[OK] cropped_data/mar/train/mar_N3-3/A8 → cropped_data/mar/train/mar_N3-3/B-52
[OK] cropped_data/mar/train/mar_N3-3/A5 → cropped_data/mar/train/mar_N3-3/F-16
[OK] cropped_data/mar/train/mar_N3-2/A2 → cropped_data/mar/train/mar_N3-2/C-130
[OK] cropped_data/mar/train/mar_N3-2/A14 → cropped_data/mar/train/mar_N3-2/KC-135
[OK] cropped_data/mar/train/mar_N3-2/A12 → cropped_data/mar/train/mar_N3-2/TU-22
[OK] cropped_data/mar/train/mar_N3-2/A9 → cropped_data/mar/train/mar_N3-2/P-3C
[OK] cropped_data/mar/train/mar_N3-2/A17 → cropped_data/mar/train/mar_N3-2/TU-95
[OK] cropped_data/mar/train/mar_N3-2/A20 → cropped_data/mar/train/mar_N3-2/SU-24
[OK] cropped_data/mar/train/mar_N3-2/A15 → cropped_data/mar/train/mar_N3-2/F-22
[OK] cropped_data/mar/train/mar_N3-2/A7 → cropped_data/mar/train/mar_N3-2/E-3
[OK] cropped_data/mar/train/mar_N3-2/A11 → cropped_data/mar/train/mar_N3-2/E-8
[OK] cropped_data/mar/train/mar_N3-2/A1 → cropped_data/mar/train/mar_N3-2/SU-35
[OK] cropped_data/mar/train/mar_N3-2/A6 → cropped_data/mar/train/mar_N3-2/TU-160
[OK] cropped_data/mar/train/mar_N3-2/A13 → cropped_data/mar/train/mar_N3-2/F-15
[OK] cropped_data/mar/train/mar_N3-2/A10 → cropped_data/mar/train/mar_N3-2/B-1B
[OK] cropped_data/mar/train/mar_N3-2/A4 → cropped_data/mar/train/mar_N3-2/C-5
[OK] cropped_data/mar/train/mar_N3-2/A19 → cropped_data/mar/train/mar_N3-2/SU-34
[OK] cropped_data/mar/train/mar_N3-2/A18 → cropped_data/mar/train/mar_N3-2/KC-1
[OK] cropped_data/mar/train/mar_N3-2/A16 → cropped_data/mar/train/mar_N3-2/FA-18
[OK] cropped_data/mar/train/mar_N3-2/A3 → cropped_data/mar/train/mar_N3-2/C-17
[OK] cropped_data/mar/train/mar_N3-2/A8 → cropped_data/mar/train/mar_N3-2/B-52
[OK] cropped_data/mar/train/mar_N3-2/A5 → cropped_data/mar/train/mar_N3-2/F-16
[OK] cropped_data/mar/train/mar_N5-1/A2 → cropped_data/mar/train/mar_N5-1/C-130
[OK] cropped_data/mar/train/mar_N5-1/A14 → cropped_data/mar/train/mar_N5-1/KC-135
[OK] cropped_data/mar/train/mar_N5-1/A12 → cropped_data/mar/train/mar_N5-1/TU-22
[OK] cropped_data/mar/train/mar_N5-1/A9 → cropped_data/mar/train/mar_N5-1/P-3C
[OK] cropped_data/mar/train/mar_N5-1/A17 → cropped_data/mar/train/mar_N5-1/TU-95
[OK] cropped_data/mar/train/mar_N5-1/A20 → cropped_data/mar/train/mar_N5-1/SU-24
[OK] cropped_data/mar/train/mar_N5-1/A15 → cropped_data/mar/train/mar_N5-1/F-22
[OK] cropped_data/mar/train/mar_N5-1/A7 → cropped_data/mar/train/mar_N5-1/E-3
[OK] cropped_data/mar/train/mar_N5-1/A11 → cropped_data/mar/train/mar_N5-1/E-8
[OK] cropped_data/mar/train/mar_N5-1/A1 → cropped_data/mar/train/mar_N5-1/SU-35
[OK] cropped_data/mar/train/mar_N5-1/A6 → cropped_data/mar/train/mar_N5-1/TU-160
[OK] cropped_data/mar/train/mar_N5-1/A13 → cropped_data/mar/train/mar_N5-1/F-15
[OK] cropped_data/mar/train/mar_N5-1/A10 → cropped_data/mar/train/mar_N5-1/B-1B
[OK] cropped_data/mar/train/mar_N5-1/A4 → cropped_data/mar/train/mar_N5-1/C-5
[OK] cropped_data/mar/train/mar_N5-1/A19 → cropped_data/mar/train/mar_N5-1/SU-34
[OK] cropped_data/mar/train/mar_N5-1/A18 → cropped_data/mar/train/mar_N5-1/KC-1
[OK] cropped_data/mar/train/mar_N5-1/A16 → cropped_data/mar/train/mar_N5-1/FA-18
[OK] cropped_data/mar/train/mar_N5-1/A3 → cropped_data/mar/train/mar_N5-1/C-17
[OK] cropped_data/mar/train/mar_N5-1/A8 → cropped_data/mar/train/mar_N5-1/B-52
[OK] cropped_data/mar/train/mar_N5-1/A5 → cropped_data/mar/train/mar_N5-1/F-16
[OK] cropped_data/mar/train/mar_N3-1/A2 → cropped_data/mar/train/mar_N3-1/C-130
[OK] cropped_data/mar/train/mar_N3-1/A14 → cropped_data/mar/train/mar_N3-1/KC-135
[OK] cropped_data/mar/train/mar_N3-1/A12 → cropped_data/mar/train/mar_N3-1/TU-22
[OK] cropped_data/mar/train/mar_N3-1/A9 → cropped_data/mar/train/mar_N3-1/P-3C
[OK] cropped_data/mar/train/mar_N3-1/A17 → cropped_data/mar/train/mar_N3-1/TU-95
[OK] cropped_data/mar/train/mar_N3-1/A20 → cropped_data/mar/train/mar_N3-1/SU-24
[OK] cropped_data/mar/train/mar_N3-1/A15 → cropped_data/mar/train/mar_N3-1/F-22
[OK] cropped_data/mar/train/mar_N3-1/A7 → cropped_data/mar/train/mar_N3-1/E-3
[OK] cropped_data/mar/train/mar_N3-1/A11 → cropped_data/mar/train/mar_N3-1/E-8
[OK] cropped_data/mar/train/mar_N3-1/A1 → cropped_data/mar/train/mar_N3-1/SU-35
[OK] cropped_data/mar/train/mar_N3-1/A6 → cropped_data/mar/train/mar_N3-1/TU-160
[OK] cropped_data/mar/train/mar_N3-1/A13 → cropped_data/mar/train/mar_N3-1/F-15
[OK] cropped_data/mar/train/mar_N3-1/A10 → cropped_data/mar/train/mar_N3-1/B-1B
[OK] cropped_data/mar/train/mar_N3-1/A4 → cropped_data/mar/train/mar_N3-1/C-5
[OK] cropped_data/mar/train/mar_N3-1/A19 → cropped_data/mar/train/mar_N3-1/SU-34
[OK] cropped_data/mar/train/mar_N3-1/A18 → cropped_data/mar/train/mar_N3-1/KC-1
[OK] cropped_data/mar/train/mar_N3-1/A16 → cropped_data/mar/train/mar_N3-1/FA-18
[OK] cropped_data/mar/train/mar_N3-1/A3 → cropped_data/mar/train/mar_N3-1/C-17
[OK] cropped_data/mar/train/mar_N3-1/A8 → cropped_data/mar/train/mar_N3-1/B-52
[OK] cropped_data/mar/train/mar_N3-1/A5 → cropped_data/mar/train/mar_N3-1/F-16
[OK] cropped_data/mar/train/mar_N30-3/A2 → cropped_data/mar/train/mar_N30-3/C-130
[OK] cropped_data/mar/train/mar_N30-3/A14 → cropped_data/mar/train/mar_N30-3/KC-135
[OK] cropped_data/mar/train/mar_N30-3/A12 → cropped_data/mar/train/mar_N30-3/TU-22
[OK] cropped_data/mar/train/mar_N30-3/A9 → cropped_data/mar/train/mar_N30-3/P-3C
[OK] cropped_data/mar/train/mar_N30-3/A17 → cropped_data/mar/train/mar_N30-3/TU-95
[OK] cropped_data/mar/train/mar_N30-3/A20 → cropped_data/mar/train/mar_N30-3/SU-24
[OK] cropped_data/mar/train/mar_N30-3/A15 → cropped_data/mar/train/mar_N30-3/F-22
[OK] cropped_data/mar/train/mar_N30-3/A7 → cropped_data/mar/train/mar_N30-3/E-3
[OK] cropped_data/mar/train/mar_N30-3/A11 → cropped_data/mar/train/mar_N30-3/E-8
[OK] cropped_data/mar/train/mar_N30-3/A1 → cropped_data/mar/train/mar_N30-3/SU-35
[OK] cropped_data/mar/train/mar_N30-3/A6 → cropped_data/mar/train/mar_N30-3/TU-160
[OK] cropped_data/mar/train/mar_N30-3/A13 → cropped_data/mar/train/mar_N30-3/F-15
[OK] cropped_data/mar/train/mar_N30-3/A10 → cropped_data/mar/train/mar_N30-3/B-1B
[OK] cropped_data/mar/train/mar_N30-3/A4 → cropped_data/mar/train/mar_N30-3/C-5
[OK] cropped_data/mar/train/mar_N30-3/A19 → cropped_data/mar/train/mar_N30-3/SU-34
[OK] cropped_data/mar/train/mar_N30-3/A18 → cropped_data/mar/train/mar_N30-3/KC-1
[OK] cropped_data/mar/train/mar_N30-3/A16 → cropped_data/mar/train/mar_N30-3/FA-18
[OK] cropped_data/mar/train/mar_N30-3/A3 → cropped_data/mar/train/mar_N30-3/C-17
[OK] cropped_data/mar/train/mar_N30-3/A8 → cropped_data/mar/train/mar_N30-3/B-52
[OK] cropped_data/mar/train/mar_N30-3/A5 → cropped_data/mar/train/mar_N30-3/F-16
[OK] cropped_data/mar/train/mar_N10-3/A2 → cropped_data/mar/train/mar_N10-3/C-130
[OK] cropped_data/mar/train/mar_N10-3/A14 → cropped_data/mar/train/mar_N10-3/KC-135
[OK] cropped_data/mar/train/mar_N10-3/A12 → cropped_data/mar/train/mar_N10-3/TU-22
[OK] cropped_data/mar/train/mar_N10-3/A9 → cropped_data/mar/train/mar_N10-3/P-3C
[OK] cropped_data/mar/train/mar_N10-3/A17 → cropped_data/mar/train/mar_N10-3/TU-95
[OK] cropped_data/mar/train/mar_N10-3/A20 → cropped_data/mar/train/mar_N10-3/SU-24
[OK] cropped_data/mar/train/mar_N10-3/A15 → cropped_data/mar/train/mar_N10-3/F-22
[OK] cropped_data/mar/train/mar_N10-3/A7 → cropped_data/mar/train/mar_N10-3/E-3
[OK] cropped_data/mar/train/mar_N10-3/A11 → cropped_data/mar/train/mar_N10-3/E-8
[OK] cropped_data/mar/train/mar_N10-3/A1 → cropped_data/mar/train/mar_N10-3/SU-35
[OK] cropped_data/mar/train/mar_N10-3/A6 → cropped_data/mar/train/mar_N10-3/TU-160
[OK] cropped_data/mar/train/mar_N10-3/A13 → cropped_data/mar/train/mar_N10-3/F-15
[OK] cropped_data/mar/train/mar_N10-3/A10 → cropped_data/mar/train/mar_N10-3/B-1B
[OK] cropped_data/mar/train/mar_N10-3/A4 → cropped_data/mar/train/mar_N10-3/C-5
[OK] cropped_data/mar/train/mar_N10-3/A19 → cropped_data/mar/train/mar_N10-3/SU-34
[OK] cropped_data/mar/train/mar_N10-3/A18 → cropped_data/mar/train/mar_N10-3/KC-1
[OK] cropped_data/mar/train/mar_N10-3/A16 → cropped_data/mar/train/mar_N10-3/FA-18
[OK] cropped_data/mar/train/mar_N10-3/A3 → cropped_data/mar/train/mar_N10-3/C-17
[OK] cropped_data/mar/train/mar_N10-3/A8 → cropped_data/mar/train/mar_N10-3/B-52
[OK] cropped_data/mar/train/mar_N10-3/A5 → cropped_data/mar/train/mar_N10-3/F-16
[OK] cropped_data/mar/train/mar_N30-2/A2 → cropped_data/mar/train/mar_N30-2/C-130
[OK] cropped_data/mar/train/mar_N30-2/A14 → cropped_data/mar/train/mar_N30-2/KC-135
[OK] cropped_data/mar/train/mar_N30-2/A12 → cropped_data/mar/train/mar_N30-2/TU-22
[OK] cropped_data/mar/train/mar_N30-2/A9 → cropped_data/mar/train/mar_N30-2/P-3C
[OK] cropped_data/mar/train/mar_N30-2/A17 → cropped_data/mar/train/mar_N30-2/TU-95
[OK] cropped_data/mar/train/mar_N30-2/A20 → cropped_data/mar/train/mar_N30-2/SU-24
[OK] cropped_data/mar/train/mar_N30-2/A15 → cropped_data/mar/train/mar_N30-2/F-22
[OK] cropped_data/mar/train/mar_N30-2/A7 → cropped_data/mar/train/mar_N30-2/E-3
[OK] cropped_data/mar/train/mar_N30-2/A11 → cropped_data/mar/train/mar_N30-2/E-8
[OK] cropped_data/mar/train/mar_N30-2/A1 → cropped_data/mar/train/mar_N30-2/SU-35
[OK] cropped_data/mar/train/mar_N30-2/A6 → cropped_data/mar/train/mar_N30-2/TU-160
[OK] cropped_data/mar/train/mar_N30-2/A13 → cropped_data/mar/train/mar_N30-2/F-15
[OK] cropped_data/mar/train/mar_N30-2/A10 → cropped_data/mar/train/mar_N30-2/B-1B
[OK] cropped_data/mar/train/mar_N30-2/A4 → cropped_data/mar/train/mar_N30-2/C-5
[OK] cropped_data/mar/train/mar_N30-2/A19 → cropped_data/mar/train/mar_N30-2/SU-34
[OK] cropped_data/mar/train/mar_N30-2/A18 → cropped_data/mar/train/mar_N30-2/KC-1
[OK] cropped_data/mar/train/mar_N30-2/A16 → cropped_data/mar/train/mar_N30-2/FA-18
[OK] cropped_data/mar/train/mar_N30-2/A3 → cropped_data/mar/train/mar_N30-2/C-17
[OK] cropped_data/mar/train/mar_N30-2/A8 → cropped_data/mar/train/mar_N30-2/B-52
[OK] cropped_data/mar/train/mar_N30-2/A5 → cropped_data/mar/train/mar_N30-2/F-16
[OK] cropped_data/mar/train/mar_N1-3/A2 → cropped_data/mar/train/mar_N1-3/C-130
[OK] cropped_data/mar/train/mar_N1-3/A14 → cropped_data/mar/train/mar_N1-3/KC-135
[OK] cropped_data/mar/train/mar_N1-3/A12 → cropped_data/mar/train/mar_N1-3/TU-22
[OK] cropped_data/mar/train/mar_N1-3/A9 → cropped_data/mar/train/mar_N1-3/P-3C
[OK] cropped_data/mar/train/mar_N1-3/A17 → cropped_data/mar/train/mar_N1-3/TU-95
[OK] cropped_data/mar/train/mar_N1-3/A20 → cropped_data/mar/train/mar_N1-3/SU-24
[OK] cropped_data/mar/train/mar_N1-3/A15 → cropped_data/mar/train/mar_N1-3/F-22
[OK] cropped_data/mar/train/mar_N1-3/A7 → cropped_data/mar/train/mar_N1-3/E-3
[OK] cropped_data/mar/train/mar_N1-3/A11 → cropped_data/mar/train/mar_N1-3/E-8
[OK] cropped_data/mar/train/mar_N1-3/A1 → cropped_data/mar/train/mar_N1-3/SU-35
[OK] cropped_data/mar/train/mar_N1-3/A6 → cropped_data/mar/train/mar_N1-3/TU-160
[OK] cropped_data/mar/train/mar_N1-3/A13 → cropped_data/mar/train/mar_N1-3/F-15
[OK] cropped_data/mar/train/mar_N1-3/A10 → cropped_data/mar/train/mar_N1-3/B-1B
[OK] cropped_data/mar/train/mar_N1-3/A4 → cropped_data/mar/train/mar_N1-3/C-5
[OK] cropped_data/mar/train/mar_N1-3/A19 → cropped_data/mar/train/mar_N1-3/SU-34
[OK] cropped_data/mar/train/mar_N1-3/A18 → cropped_data/mar/train/mar_N1-3/KC-1
[OK] cropped_data/mar/train/mar_N1-3/A16 → cropped_data/mar/train/mar_N1-3/FA-18
[OK] cropped_data/mar/train/mar_N1-3/A3 → cropped_data/mar/train/mar_N1-3/C-17
[OK] cropped_data/mar/train/mar_N1-3/A8 → cropped_data/mar/train/mar_N1-3/B-52
[OK] cropped_data/mar/train/mar_N1-3/A5 → cropped_data/mar/train/mar_N1-3/F-16
[OK] cropped_data/mar/train/mar_N1-2/A2 → cropped_data/mar/train/mar_N1-2/C-130
[OK] cropped_data/mar/train/mar_N1-2/A14 → cropped_data/mar/train/mar_N1-2/KC-135
[OK] cropped_data/mar/train/mar_N1-2/A12 → cropped_data/mar/train/mar_N1-2/TU-22
[OK] cropped_data/mar/train/mar_N1-2/A9 → cropped_data/mar/train/mar_N1-2/P-3C
[OK] cropped_data/mar/train/mar_N1-2/A17 → cropped_data/mar/train/mar_N1-2/TU-95
[OK] cropped_data/mar/train/mar_N1-2/A20 → cropped_data/mar/train/mar_N1-2/SU-24
[OK] cropped_data/mar/train/mar_N1-2/A15 → cropped_data/mar/train/mar_N1-2/F-22
[OK] cropped_data/mar/train/mar_N1-2/A7 → cropped_data/mar/train/mar_N1-2/E-3
[OK] cropped_data/mar/train/mar_N1-2/A11 → cropped_data/mar/train/mar_N1-2/E-8
[OK] cropped_data/mar/train/mar_N1-2/A1 → cropped_data/mar/train/mar_N1-2/SU-35
[OK] cropped_data/mar/train/mar_N1-2/A6 → cropped_data/mar/train/mar_N1-2/TU-160
[OK] cropped_data/mar/train/mar_N1-2/A13 → cropped_data/mar/train/mar_N1-2/F-15
[OK] cropped_data/mar/train/mar_N1-2/A10 → cropped_data/mar/train/mar_N1-2/B-1B
[OK] cropped_data/mar/train/mar_N1-2/A4 → cropped_data/mar/train/mar_N1-2/C-5
[OK] cropped_data/mar/train/mar_N1-2/A19 → cropped_data/mar/train/mar_N1-2/SU-34
[OK] cropped_data/mar/train/mar_N1-2/A18 → cropped_data/mar/train/mar_N1-2/KC-1
[OK] cropped_data/mar/train/mar_N1-2/A16 → cropped_data/mar/train/mar_N1-2/FA-18
[OK] cropped_data/mar/train/mar_N1-2/A3 → cropped_data/mar/train/mar_N1-2/C-17
[OK] cropped_data/mar/train/mar_N1-2/A8 → cropped_data/mar/train/mar_N1-2/B-52
[OK] cropped_data/mar/train/mar_N1-2/A5 → cropped_data/mar/train/mar_N1-2/F-16
[OK] cropped_data/mar/train/mar_N10-2/A2 → cropped_data/mar/train/mar_N10-2/C-130
[OK] cropped_data/mar/train/mar_N10-2/A14 → cropped_data/mar/train/mar_N10-2/KC-135
[OK] cropped_data/mar/train/mar_N10-2/A12 → cropped_data/mar/train/mar_N10-2/TU-22
[OK] cropped_data/mar/train/mar_N10-2/A9 → cropped_data/mar/train/mar_N10-2/P-3C
[OK] cropped_data/mar/train/mar_N10-2/A17 → cropped_data/mar/train/mar_N10-2/TU-95
[OK] cropped_data/mar/train/mar_N10-2/A20 → cropped_data/mar/train/mar_N10-2/SU-24
[OK] cropped_data/mar/train/mar_N10-2/A15 → cropped_data/mar/train/mar_N10-2/F-22
[OK] cropped_data/mar/train/mar_N10-2/A7 → cropped_data/mar/train/mar_N10-2/E-3
[OK] cropped_data/mar/train/mar_N10-2/A11 → cropped_data/mar/train/mar_N10-2/E-8
[OK] cropped_data/mar/train/mar_N10-2/A1 → cropped_data/mar/train/mar_N10-2/SU-35
[OK] cropped_data/mar/train/mar_N10-2/A6 → cropped_data/mar/train/mar_N10-2/TU-160
[OK] cropped_data/mar/train/mar_N10-2/A13 → cropped_data/mar/train/mar_N10-2/F-15
[OK] cropped_data/mar/train/mar_N10-2/A10 → cropped_data/mar/train/mar_N10-2/B-1B
[OK] cropped_data/mar/train/mar_N10-2/A4 → cropped_data/mar/train/mar_N10-2/C-5
[OK] cropped_data/mar/train/mar_N10-2/A19 → cropped_data/mar/train/mar_N10-2/SU-34
[OK] cropped_data/mar/train/mar_N10-2/A18 → cropped_data/mar/train/mar_N10-2/KC-1
[OK] cropped_data/mar/train/mar_N10-2/A16 → cropped_data/mar/train/mar_N10-2/FA-18
[OK] cropped_data/mar/train/mar_N10-2/A3 → cropped_data/mar/train/mar_N10-2/C-17
[OK] cropped_data/mar/train/mar_N10-2/A8 → cropped_data/mar/train/mar_N10-2/B-52
[OK] cropped_data/mar/train/mar_N10-2/A5 → cropped_data/mar/train/mar_N10-2/F-16
[OK] cropped_data/mar/train/mar_N5-2/A2 → cropped_data/mar/train/mar_N5-2/C-130
[OK] cropped_data/mar/train/mar_N5-2/A14 → cropped_data/mar/train/mar_N5-2/KC-135
[OK] cropped_data/mar/train/mar_N5-2/A12 → cropped_data/mar/train/mar_N5-2/TU-22
[OK] cropped_data/mar/train/mar_N5-2/A9 → cropped_data/mar/train/mar_N5-2/P-3C
[OK] cropped_data/mar/train/mar_N5-2/A17 → cropped_data/mar/train/mar_N5-2/TU-95
[OK] cropped_data/mar/train/mar_N5-2/A20 → cropped_data/mar/train/mar_N5-2/SU-24
[OK] cropped_data/mar/train/mar_N5-2/A15 → cropped_data/mar/train/mar_N5-2/F-22
[OK] cropped_data/mar/train/mar_N5-2/A7 → cropped_data/mar/train/mar_N5-2/E-3
[OK] cropped_data/mar/train/mar_N5-2/A11 → cropped_data/mar/train/mar_N5-2/E-8
[OK] cropped_data/mar/train/mar_N5-2/A1 → cropped_data/mar/train/mar_N5-2/SU-35
[OK] cropped_data/mar/train/mar_N5-2/A6 → cropped_data/mar/train/mar_N5-2/TU-160
[OK] cropped_data/mar/train/mar_N5-2/A13 → cropped_data/mar/train/mar_N5-2/F-15
[OK] cropped_data/mar/train/mar_N5-2/A10 → cropped_data/mar/train/mar_N5-2/B-1B
[OK] cropped_data/mar/train/mar_N5-2/A4 → cropped_data/mar/train/mar_N5-2/C-5
[OK] cropped_data/mar/train/mar_N5-2/A19 → cropped_data/mar/train/mar_N5-2/SU-34
[OK] cropped_data/mar/train/mar_N5-2/A18 → cropped_data/mar/train/mar_N5-2/KC-1
[OK] cropped_data/mar/train/mar_N5-2/A16 → cropped_data/mar/train/mar_N5-2/FA-18
[OK] cropped_data/mar/train/mar_N5-2/A3 → cropped_data/mar/train/mar_N5-2/C-17
[OK] cropped_data/mar/train/mar_N5-2/A8 → cropped_data/mar/train/mar_N5-2/B-52
[OK] cropped_data/mar/train/mar_N5-2/A5 → cropped_data/mar/train/mar_N5-2/F-16
[OK] cropped_data/mar/train/mar_N30-1/A2 → cropped_data/mar/train/mar_N30-1/C-130
[OK] cropped_data/mar/train/mar_N30-1/A14 → cropped_data/mar/train/mar_N30-1/KC-135
[OK] cropped_data/mar/train/mar_N30-1/A12 → cropped_data/mar/train/mar_N30-1/TU-22
[OK] cropped_data/mar/train/mar_N30-1/A9 → cropped_data/mar/train/mar_N30-1/P-3C
[OK] cropped_data/mar/train/mar_N30-1/A17 → cropped_data/mar/train/mar_N30-1/TU-95
[OK] cropped_data/mar/train/mar_N30-1/A20 → cropped_data/mar/train/mar_N30-1/SU-24
[OK] cropped_data/mar/train/mar_N30-1/A15 → cropped_data/mar/train/mar_N30-1/F-22